import type { Preset } from './types';
import { DynamicStyle, ParticleBehavior, BackgroundBehavior, LogoBehavior } from './types';

export const ALL_STYLES: Preset[] = [
  {
    name: 'Pyro Burst',
    dynamicStyle: DynamicStyle.PyroBurst,
    motionIntensity: 2.5,
    cameraShakeIntensity: 2.0,
    barCount: 150,
    barWidth: 3,
    glowRadius: 30,
    starSpikes: 5,
    starInnerRadius: 0.5,
    spectrumColor1: '#FFA500',
    spectrumColor2: '#FF4500',
    bgColor1: '#000000',
    bgColor2: '#1a0000',
    particleColor: '#FFD700',
    logoSize: 1.0,
    highEnergyFx: true,
    smoothingTimeConstant: 0.7,
    frequencyRangeStart: 0,
    frequencyRangeEnd: 1,
    particleBehavior: ParticleBehavior.Gravity, // Note: Behavior is custom in App.tsx
    backgroundBehavior: BackgroundBehavior.AudioPulse,
    logoBehavior: LogoBehavior.Pulse,
  },
    {
    name: 'Glacial Shards',
    dynamicStyle: DynamicStyle.GlacialShards,
    motionIntensity: 1.6,
    cameraShakeIntensity: 1.0,
    barCount: 128,
    barWidth: 2,
    glowRadius: 22,
    starSpikes: 8,
    starInnerRadius: 0.4,
    spectrumColor1: '#00FFFF',
    spectrumColor2: '#ADD8E6',
    bgColor1: '#000015',
    bgColor2: '#050520',
    particleColor: '#FFFFFF',
    logoSize: 1.0,
    highEnergyFx: true,
    smoothingTimeConstant: 0.8,
    frequencyRangeStart: 0,
    frequencyRangeEnd: 1,
    particleBehavior: ParticleBehavior.Static, // Custom shard logic used
    backgroundBehavior: BackgroundBehavior.GentleZoom,
    logoBehavior: LogoBehavior.Pulse,
  },
  {
    name: 'Quantum Entanglement',
    dynamicStyle: DynamicStyle.QuantumEntanglement,
    motionIntensity: 2.0,
    cameraShakeIntensity: 1.2,
    barCount: 1, // Visualizer not used, only particles
    barWidth: 1,
    glowRadius: 10,
    starSpikes: 5,
    starInnerRadius: 0.5,
    spectrumColor1: '#39FF14',
    spectrumColor2: '#00FFFF',
    bgColor1: '#000008',
    bgColor2: '#000500',
    particleColor: '#FFFFFF',
    logoSize: 1.0,
    highEnergyFx: false,
    smoothingTimeConstant: 0.6,
    frequencyRangeStart: 0,
    frequencyRangeEnd: 1,
    particleBehavior: ParticleBehavior.Static, // Custom quantum logic used
    backgroundBehavior: BackgroundBehavior.Static,
    logoBehavior: LogoBehavior.Pulse,
  },
  {
    name: 'Celestial Bloom',
    dynamicStyle: DynamicStyle.CelestialBloom,
    motionIntensity: 1.5,
    cameraShakeIntensity: 0.2,
    barCount: 180,
    barWidth: 2,
    glowRadius: 35,
    starSpikes: 10,
    starInnerRadius: 0.3,
    spectrumColor1: '#FFD700',
    spectrumColor2: '#8A2BE2',
    bgColor1: '#020024',
    bgColor2: '#090979',
    particleColor: '#F0E68C',
    logoSize: 1.0,
    highEnergyFx: false,
    smoothingTimeConstant: 0.85,
    frequencyRangeStart: 0,
    frequencyRangeEnd: 1,
    particleBehavior: ParticleBehavior.RadialOut,
    backgroundBehavior: BackgroundBehavior.GentleZoom,
    logoBehavior: LogoBehavior.Float,
  },
];


export const INITIAL_CONFIG = ALL_STYLES[0];